parameters:
  - name: DebugMode
    displayName: Run the Pipeline in Debug Mode
    type: boolean
    default: false

  - name: DebugModePython
    displayName: Run the python script in Debug Mode
    type: boolean
    default: false


variables:
  - name: System.Debug
    value: ${{ parameters.DebugMode }}

  
pr:
  branches:
    include:
    - pipelines
    - main
    - releases/*
  drafts: false
trigger:
  branches:
    include:
      - main
      - pipelines
      - refs/tags/*

stages:
  - stage: buildAndRun
    displayName:  'Build and Run' 
    jobs:
    - job: buildRun
      displayName: buildRun
      steps:

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
        displayName: Setting up Python

      - bash: pip install -r requirements.txt
        displayName: 'Installing pip requirements' 

      - bash: python main.py --debug '${{parameters.DebugModePython}}'
        displayName: 'Running python main.py'

      - publish: epd_data.json
        artifact: epd_data.json